namespace XynokSourceGenerator.Core.Const
{
    public class Keyword
    {
        public const string Author = "/*--- This file is automatically generated by Xynok Codex, dont modify it manually. ---*/\n";

        
        /// <summary>
        /// dùng để filter name của enum
        /// </summary>
        public static string[] GroupSuffixs = new[] { "ID", "IDs", "Id", "Ids", "Type", "Group", "Collection" };
        public const string SuffixGen = ".g";
        public const string CsFile = ".cs";
    }
}